# Site settings
title: Agus Ibrahim 
description: Agus Ibrahim Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Agus Ibrahim
user_description: You have an Idea. We have the software experts, who bring it to life.
user_title: Mobile Apps Developer, User Experience Designer
email: pymobile123@gmail.com
twitter_username: agusmibrahim
github_username:  agusibrahim
gplus_username:  agusibrahim

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

sitemap-force-include:
- "/.well-known/*.json"

defaults:
  - scope:
      path: ".well-known"
    values:
      image: false
